backport: Backport i915_component.h header
From 6.18 onwards, new enum member is added in i915_component_type,
instead of backporting enum add complete header in copy-list.

Error:
-------------------------------------------------------------------------------
error: ‘INTEL_COMPONENT_LB’ undeclared
-------------------------------------------------------------------------------

Reference:
    741eeabb7c78 mei: late_bind: add late binding component driver

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>