autotools/m4: Add probe for for_each_if
Add a probe to detect if for_each_if() is natively available
in the target kernel's headers. If the macro is missing, the probe
defines the appropriate backport flag (BPM_FOR_EACH_IF_NOT_PRESENT)

error:
-------------------------------------------------------------------------
gpu_scheduler.h:751: implicit declaration of function 'for_each_if'
-------------------------------------------------------------------------

Reference:
   b2108fc82a0a
   drm: Move for_each_if() to util_macros.h for wider use

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Varun Gupta <varun.gupta@intel.com>