Backport DEFINE_SHOW_STORE_ATTRIBUTE() macro
DEFINE_SHOW_STORE_ATTRIBUTE() macro has been introduced from 6.7 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, backported DEFINE_SHOW_STORE_ATTRIBUTE() macro for
below 6.6 kernels.

Error:
-------------------------------------------------------------------------------
error: type defaults to ‘int’ in declaration of ‘DEFINE_SHOW_STORE_ATTRIBUTE’
error: ‘force_reset_fops’ undeclared
error: ‘force_reset_sync_fops’ undeclared
warning: ‘force_reset_sync_show’ defined but not used
warning: ‘force_reset_sync_write’ defined but not used
warning: ‘force_reset_show’ defined but not used
warning: ‘force_reset_write’ defined but not used
-------------------------------------------------------------------------------

Reference:
	9cba82bba500 seq_file: add helper macro to define attribute for rw file

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>