Use register_shrinker instead of shrinker_register for below 6.7 kernels
register_shrinker() api is replaced with shrinker_alloc() and
shrinker_register() from 6.7 kernel.
Also unregister_shrinker() is replaced with shrinker_free().
Also member private_data has been added into struct shrink to store xe
driver shrink struct.
Hence observing below errors.
To fix these errors, used older apis for below 6.7 kernels.

Errors:
------------------------------------------------------------------------------
error: ‘struct shrinker’ has no member named ‘private_data’
error: implicit declaration of function 'shrinker_alloc'
error: implicit declaration of function 'shrinker_register'
error: implicit declaration of function 'shrinker_free'
------------------------------------------------------------------------------

Reference:
        c42d50aefd17
        mm: shrinker: add infrastructure for dynamically allocating shrinker

Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>