autotools/m4: Backport DIV_U64_ROUND_UP macro
DIV_U64_ROUND_UP macro is introduced from 6.11 kernel.
Hence below error is observing for 6.6 compilation.
To fix this error, backported DIV_U64_ROUND_UP macro for below 6.11 kernel.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘DIV_U64_ROUND_UP
-----------------------------------------------------------------------

Reference:
	1d4ce389da2b
	ice: add and use roundup_u64 instead of open coding equivalent

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>