Use EXPORT_SYMBOL() instead of EXPORT_SYMBOL_FOR_MODULES
EXPORT_SYMBOL_FOR_MODULES() macro is not avilable in 6.6 kernel.
Hence observing below errors.
To fix these errors, EXPORT_SYMBOL() macro is present in
place of EXPORT_SYMBOL_FOR_MODULES() macro.
Hence replaced EXPORT_SYMBOL_FOR_MODULES with EXPORT_SYMBOL() for 6.6 kernel.

Errors:
-------------------------------------------------------------------------------
error: expected ‘)’ before string constant
-------------------------------------------------------------------------------

Reference:
	6d3c3ca4c77e
	module: Rename EXPORT_SYMBOL_GPL_FOR_MODULES to EXPORT_SYMBOL_FOR_MODULES

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>