autotools/m4: Use cancel_work_sync instead of disable_work_sync
cancel_work_sync() api has been renamed as disable_work_sync from 6.10 kernel.
Hence observing below error for 6.6 kernel.
To fix this error, replaced disable_work_sync() with cancel_work_sync()
for below 6.10 kernels.

Error:
-----------------------------------------------------------------------
error: implicit declaration of function ‘disable_work_sync’
-----------------------------------------------------------------------

Reference:
        86898fa6b8cd
        workqueue: Implement disable/enable for (delayed) work items

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>