autotools/m4: manage drm_buddy_free_list prototype
Introduced 3rd argument for drm_buddy_free_list() api from kv 6.11,
which causes below issue.

Error:
-------------------------------------------------------------------------------
too many arguments to function drm_buddy_free_list
-------------------------------------------------------------------------------

Backport drm_buddy_free_list with 2 arguments for 6.8 KV to resolve it.

Reference:
    96950929eb23
    drm/buddy: Implement tracking clear page feature

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>