autotools/m4: manage drm_buddy_block_trim availability
Starting from KV 6.11, a new start parameter has been added as a second
argument in the drm_buddy_block_trim function to specify the exact
address from where to start trimming.

Use drm_buddy_block_trim() base kenrel api without second argument
for kv 6.8 to resolve below issue.

Error:
-------------------------------------------------------------------------------
too many arguments to function _drm_buddy_block_trim
-------------------------------------------------------------------------------

Reference:
    d507ae0dc83b
    drm/buddy: Add start address support to trim function

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>