autotools/m4: Backport DEFINE_SYSFS_GROUP_VISIBLE macro
DEFINE_SYSFS_GROUP_VISIBLE macro has been introduced from 6.17 kernel.
Hence when using this macro aginst 6.6 lts headers, observing below errors.
To fix these errors, backported DEFINE_SYSFS_GROUP_VISIBLE macro.

Errors:
-----------------------------------------------------------------------------
error: type defaults to ‘int’ in declaration of ‘DEFINE_SYSFS_GROUP_VISIBLE’
error: implicit declaration of function ‘SYSFS_GROUP_VISIBLE’
error: ‘intel_pmt’ undeclared here
------------------------------------------------------------------------------

Reference:
	d9a078809356 platform/x86/intel/pmt: Add PMT Discovery driver

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
co-authored-by: Rachapalli Bandi Jagadeesh <jagadeesh.rachapalli.bandi@intel.com>