backports: Add intel_dg_nvm_aux.h file
From KV 6.17 onwards, introduced new intel_dg_nvm_aux.h header
file for intel graphics non-volatile memory device.

Add intel_dg_nvm_aux.h file in copy-list to resolve below error.

Error:
-------------------------------------------------------------------------------
error: linux/intel_dg_nvm_aux.h: No such file or directory
-------------------------------------------------------------------------------

Reference:
    ceb5ab3cb646
    mtd: add driver for intel graphics non-volatile memory device

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>