Add support for free cleanup attribute detection
Currently, __free(bitmap) attribute is being used for automatic memory
cleanup. On kernels where this cleanup infrastructure is not available,
compilation fails as described below:

error: unsigned long *bitmap __free(bitmap) = bitmap_zalloc(allvfs, GFP_KERNEL);

This occurs because while the kernel may have the __free() macro, the
specific bitmap cleanup handler is not defined.

In order to solve this issue on target kernel 6.6KV added macro in
autotools to determine if __free(bitmap) is supported by the target kernel.
If available, use the automatic cleanup attribute else fall back to standard
variable declaration.

Reviewed-by: Syed Abdul Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Reviewed-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>
Signed-off-by: Akanksha Hotta <akanksha.hotta@intel.com>