autotools/m4: manage prototype changes in strscpy
strscpy has moved to dynamic size calculation and only 2 arguments are
present in KV6.9. use alternative for older kernels.

Error:
--------------------------------------------------------------------------
error: too few arguments to function _strscpy
--------------------------------------------------------------------------

Reference:
    e6584c3964f2 string: Allow 2-argument strscpy()

Reviewed-by: Ayaz A Siddiqui <ayaz.siddiqui@intel.com>
Signed-off-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>