autotools/m4: manage FOP_UNSIGNED_OFFSET availability
From KV 6.12 onwards, FMODE_UNSIGNED_OFFSET is moved under fop_flags.

manage FOP_UNSIGNED_OFFSET availability by using m4 function if it is
not present in base kernel.

Error:
-------------------------------------------------------------------------------
‘const struct file_operations’ has no member named ‘fop_flags’
-------------------------------------------------------------------------------

Reference:
    641bb4394f405 fs: move FMODE_UNSIGNED_OFFSET to fop_flags

Reviewed-by: S A Muqthyar Ahmed <syed.abdul.muqthyar.ahmed@intel.com>
Signed-off-by: Kanaka Raju Nayana <kanaka.raju.nayana@intel.com>